# Name of the workflow
name: Deploy Flask App

# Specifies when the workflow should be triggered
on:
  # Triggers the workflow on every push
  push:
    # Specifies that the workflow should only be triggered on pushes to the 'main' branch
    branches:
      - main

# Defines the jobs for the workflow
jobs:
  # Defines a job named 'build'
  build:
    # Specifies the type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # Defines the steps for the job
    steps:
      # Step 1: Checks out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Sets up QEMU.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 3: Sets up Docker Buildx.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Logs in to Docker Hub.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Builds and pushes the Docker image.
      # The image will be pushed to a private repository if the repository 'beltus/web-frameworks' is set to private on Docker Hub.
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: beltus/web-frameworks/fs:latest
